### ISSUE TITLE
Need to make build-output logs shorter/fully viewable (at least in Travis CI)

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxapom#210]
We need to make the build-log output much shorter -- at least for Travis CI.

See https://travis-ci.org/mozilla/fxapom/jobs/349606259 and https://travis-ci.org/mozilla/fxapom/jobs/349606259#L2452-L2460, particularly.

<img width="1792" alt="screen shot 2018-03-05 at 10 48 03 pm" src="https://user-images.githubusercontent.com/387249/37017959-661ce67e-20c7-11e8-9b9d-9fda4e00fb75.png">

**Comment by davehunt** [comment]
This appears to be a regression from aa0fa5f004875c666c0db91fe1084d15333c51cc where we're using curl to download get-pip, but instead of executing it, we're just dumping it to the console. This might also explain #207.

You could try replacing `RUN curl -fsSL https://bootstrap.pypa.io/get-pip.py` with `RUN curl -fsSL https://bootstrap.pypa.io/get-pip.py | python`, but as we already have pip installed, you could probably just remove this line entirely.

**Comment by stephendonner** [comment]
Thanks, Dave.

With https://github.com/mozilla/fxapom/pull/207/files in master now, I'm able to build just fine, without warnings: https://gist.github.com/stephendonner/a7c682b38ac2bfe28838fdd7bbc06a52

**Comment by stephendonner** [comment]
And master in Travis CI is back to its intermittent failure, but a much-shorter build log:

https://travis-ci.org/mozilla/fxapom/jobs/350013022
