### ISSUE TITLE
Error: test session has already finished

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxapom#260]
Recently, we've been seeing in Jenkins; I can't figure out what's going on, yet:

```
01:34:33 [py36] [gw1] [100%] ERROR tests/test_fxa_login.py::TestLogin::test_user_can_sign_in 
01:34:33 [py36] 
01:34:33 [py36] ==================================== ERRORS ====================================
01:34:33 [py36] ______________ ERROR at setup of TestLogin.test_user_can_sign_in _______________
01:34:33 [py36] [gw1] linux -- Python 3.6.4 /home/jenkins/slave/workspace/fxapom.stage@2/.tox/py36/bin/python3.6
01:34:33 [py36] tests/conftest.py:34: in click_login
01:34:33 [py36]     selenium.get('%s/' % base_url)
01:34:33 [py36] .tox/py36/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:332: in get
01:34:33 [py36]     self.execute(Command.GET, {'url': url})
01:34:33 [py36] .tox/py36/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:320: in execute
01:34:33 [py36]     self.error_handler.check_response(response)
01:34:33 [py36] .tox/py36/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py:208: in check_response
01:34:33 [py36]     raise exception_class(value)
01:34:33 [py36] E   selenium.common.exceptions.WebDriverException: Message: ERROR The test with session id 0c64167584914996a69f9d6dd19278c0 has already finished, and can't receive further commands.
01:34:33 [py36] E   You can learn more at https://saucelabs.com/jobs/0c64167584914996a69f9d6dd19278c0
01:34:33 [py36] E   For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
01:34:33 [py36] ------------------------------- pytest-selenium --------------------------------
01:34:33 [py36] WARNING: Failed to gather URL: Message: ERROR The test with session id 0c64167584914996a69f9d6dd19278c0 has already finished, and can't receive further commands.
01:34:33 [py36] You can learn more at https://saucelabs.com/jobs/0c64167584914996a69f9d6dd19278c0
01:34:33 [py36] For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
01:34:33 [py36] 
01:34:33 [py36] WARNING: Failed to gather screenshot: Message: ERROR The test with session id 0c64167584914996a69f9d6dd19278c0 has already finished, and can't receive further commands.
01:34:33 [py36] You can learn more at https://saucelabs.com/jobs/0c64167584914996a69f9d6dd19278c0
01:34:33 [py36] For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
01:34:33 [py36] 
01:34:33 [py36] WARNING: Failed to gather HTML: Message: ERROR The test with session id 0c64167584914996a69f9d6dd19278c0 has already finished, and can't receive further commands.
01:34:33 [py36] You can learn more at https://saucelabs.com/jobs/0c64167584914996a69f9d6dd19278c0
01:34:33 [py36] For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
01:34:33 [py36] 
01:34:33 [py36] WARNING: Failed to gather log types: Message: ERROR The test with session id 0c64167584914996a69f9d6dd19278c0 has already finished, and can't receive further commands.
01:34:33 [py36] You can learn more at https://saucelabs.com/jobs/0c64167584914996a69f9d6dd19278c0
01:34:33 [py36] For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
01:34:33 [py36] 
01:34:33 [py36] Sauce Labs Job: https://saucelabs.com/jobs/0c64167584914996a69f9d6dd19278c0
```
https://saucelabs.com/beta/tests/0c64167584914996a69f9d6dd19278c0/watch#0
https://qa-master.fxtest.jenkins.stage.mozaws.net/job/fxapom.stage/438/consoleFull

**Comment by davehunt** [comment]
This looks to me like a Sauce Labs issue. We request a session, which returns a response, but the very next command tells us that the session is already finished. Looking at the Sauce Labs job, only the session request is ever received.

**Comment by stephendonner** [comment]
Thanks, @davehunt - I suspected so, but wasn't sure (esp. with FxA / restmail interaction + failures, lately).  I've filed a support ticket (under/from sdonner@mozilla.com), and will keep this Issue updated.

**Comment by DylanLacey** [comment]
I'm with Sauce Labs Support.  I've responded to @stephendonner's ticket via our helpdesk but wanted to keep things visible for everyone else as well.

Checking out that test in particular, the timeline looks like this:

1. 01:31:57 - You request a new session
2. 01:31:37 - We create a new session VM
3. 01:31:43 - We send a response to your test runner, having bought up Firefox and Selenium
4. 01:33:45 - As we've not received a command for 90 seconds, we shut this VM down
5. 01:34:33 - Your test runner sends us a command.  We're unable to dispatch it because the VM is no longer running, so we return that error.


When people encounter this error, almost all of the time it's a legitimate error.  For whatever reason, their test runner has started sessions it doesn't interact with before they time out.  This is often due to a parallelisation problem.

So that would be my first assumption; Without any other evidence, I'd say that the first attempt to interact with a new session was over 90 seconds after it started, so we had already shut it down.

It's also possible that you had sent us some command/s, and they never reached us.  That might explain why you received that error for this command, but if that was the case I'd expect to see those commands timing out with a 500 error, or a complaint that the server doesn't exist or timed out.

You might not have received the notification that the new session had started, but again, in that case I'd expect the new session notification to have errored.  It's possible that this error here is a retry of a caught exception, but I don't have the evidence to say either way.

The best was I can think of to move forward would be to log around your Selenium commands, showing the time they were sent, responded too, and the session ID (if any).  I know the Ruby and Java bindings have built in log hooks for this but I'm not sure for Python; You might have to go spelunking through the code/docs.  You could also use a HTTP traffic logger (or just log at the Python HTTP library level).

That log will either demonstrate a timing issue with your test runner, or give us some more information about what's happening when for your side.  We can then pair it up with our logs and figure out what's causing this problem.

**Comment by davehunt** [comment]
This has only started happening recently, and there have been a few changes on our side. We've updated to the latest Python client (3.14.0) and updated to the latest version of tox (3.1.3) and pytest (3.7.1). Any (or all) of these could have introduced this intermittent, but I'd suspect the Selenium client above the others as a new dependency on urllib3 was introduced.

@stephendonner could you try reverting the Selenium client upgrade to see if these issues resolve themselves? Also, have we seen these issues on any other projects?

**Comment by davehunt** [comment]
For additional logging information we could try adding `log_level = debug` to the `[pytest]` section of `tox.ini`, or add the `--log-level=debug` command line option. This will at least give us some insight into the timings between the session request and subsequent commands.

**Comment by davehunt** [comment]
Whilst looking at the debug log output I noticed that we create our session, and then create a FxA test account. If the creation/verification of the FxA account takes a long time then it's possible the Sauce Labs session will time out. We could simply reorder the fixtures in the test method signature to make sure we have our FxA test account before we create our Selenium session. I'll open a pull request, as this is a simple change that may resolve this issue.

**Comment by DylanLacey** [comment]
Oh, neat.  Account creation would need to take more then 85ish seconds in order to trigger this, so there might be another underlying problem, but maybe we'll get lucky and re-ordering will make things good.
